### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by m-o-r-o** [ResidentMario/missingno#100]
Hi,

I am new to all of this, but found this package brilliant.  One idea I had was if the colour of the charts could reflect the cardinality of the feature/column.  So you could also determine if a field was all unique values or all the same value quite easily.

Thanks
MoRo

**Comment by ResidentMario** [comment]
Thanks for the suggestion! It's an interesting idea, but I don't think I would want to add this feature simply because the chart is pretty packed as it is in terms of visual variables. Checking cardinality of a dataframe is actually one of the easiest operations, thanks to `pandas.DataFrame.unique` et al.
