### ISSUE TITLE
SVG with missingno.matrix

### ISSUE THREAD

**Issue by jaketae** [ResidentMario/missingno#104]
Hello,

I'm slightly confused by the behavior of `missingno.matrix()` when called in Jupyter notebooks with a specific `matplotlib` configuration, namely `%config InlineBackend.figure_format = 'svg'`. Using this configuration seems to blur the matrix displaying the missing values so that white spaces bleed over to adjacent columns. For better illustration, [here](http://colab.research.google.com/gist/jaketae/ba2ef37872d54538e1144743a6a18b2b) is a link to a notebook replicating this behavior.

I'm not sure if this issue has already been reported before since my search among closed issues proved to be futile, so I thought it would be best to give it a shot here. Thank you in advance!

**Comment by ResidentMario** [comment]
Unfortunately I can't claim to support any of the `matplotlib` backends besides the standard one! In my experience the claim that `matplotlib` backends can be used independently of one another are is not really true; there are differences between how they render that make it non-trivial to switch between them. This issue is a great example of that.

[matplotlib#12609](https://github.com/matplotlib/matplotlib/issues/12609) might be related. You have a very clear example so I suggest filing this bug report in the `matplotlib` repo with the [backend/svg](https://github.com/matplotlib/matplotlib/issues?q=is%3Aissue+is%3Aopen+svg+label%3Abackend%2Fsvg) tag.

**Comment by jaketae** [comment]
Thanks for the prompt reply! For some reason, I always thought `matplotlib` backends could be switched without much consideration, but perhaps that's not really the case as demonstrated by this case. I'll consider filing an issue over at `matplotlib`.
