### ISSUE TITLE
Value Error while using missingno bar

### ISSUE THREAD

**Issue by prashant2-4-4** [ResidentMario/missingno#157]
While working on a kaggle dataset for june challenge i came across this error.

ValueError: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (81).

I am using this code

import missingno as msno
plt.figure(figsize = (20,10))
msno.bar(data)
plt.show()

Please fix the issue.

**Comment by lancedikson** [comment]
Sounds pretty much like #135 to me :) 

I also encountered the same issue on a dataset of `(10000, 53)` shape. Quick googling lead me to this issue here: https://github.com/Qiskit/qiskit/issues/990, where I picked up an idea of downgrading matplotlib to `3.2.2`, which worked pretty well except that I needed to downgrade Python version to 3.8 as well.
