### ISSUE TITLE
geoplot function would not work for me

### ISSUE THREAD

**Issue by rhiever** [ResidentMario/missingno#59]
I installed the optional dependencies then used the same data from #51. I passed it to the `geoplot` function examples from the README and these are the outputs.

![geoplot-error1](https://user-images.githubusercontent.com/1719223/35603378-eeb5bc4a-05f1-11e8-8574-591ad89e9c04.png)

![geoplot-error2](https://user-images.githubusercontent.com/1719223/35603379-f1dc31e2-05f1-11e8-8457-93f63fb40bef.png)

I don't do much geospatial dataviz in Python, so it's possible I'm missing another dependency or have a bad setting. Please let me know what package versions you would like to know, if that information is useful.

**Comment by ResidentMario** [comment]
It's quite possible that this is because `geoplot` is simply broken. It was never very well utilized, and hence, not terrifically well-maintained.

The timeline here is that after implementing this method experimentally in this package, I went and implemented a more general method, `aggplot`, in a package I published last January called [`geoplot`](https://github.com/ResidentMario/geoplot). That method is vastly better tested, and I believe also has significantly better performance characteristics. I also have not personally seen any uses of this geospatial plotting method "in the wild".

After thinking about this some, I decided to throw out the current `geoplot` method body and replace it with a thin interface to `geoplot.aggplot`. The existing methodology is a maintenance burden, `aggplot` provides a better implementation, and I doubt this will cause much user disruption. It's a backwards-incompatible change, but all things considered I'm comfortable making it.

The new method is now implemented. Let me know if you have any issues with it.
