### ISSUE TITLE
geoplot function imports packages every time it is called

### ISSUE THREAD

**Issue by rhiever** [ResidentMario/missingno#60]
The `geoplot` function imports a handful of packages every time it's called. I don't recommend doing this. I suggest you place all imports at the top of the code file.

Alternatively, place the `geoplot` function in a separate file/subdirectory of the package with the imports at the top such that the imports are invoked only when `geoplot` is imported.

This issue is somewhat related to #52.

**Comment by ResidentMario** [comment]
This was because `geoplot` requires some geospatial libraries which can be very difficult to install. Additionally, it was far and away the least used method in the library (I've never seen it used in the wild). It didn't seem justifiable to me that I add to the prerequisite burden for it, so I made the required libraries optional dependencies (in the style of, say, `xlrd` for `pandas`).

The rewritten `geoplot` method (see [here](https://github.com/ResidentMario/missingno/issues/59#issuecomment-362872126) for details on why I rewrote it) relies on the `geoplot` and `geopandas` packages. Same deal holds, though. I've gone ahead and marked them clearly as optional dependencies in the `README.md`.
