### ISSUE TITLE
subplotting

### ISSUE THREAD

**Issue by clevilll** [ResidentMario/missingno#83]
What is the easiest way to have subplots of  `msno.matrix()` for df1 , df2, df3 . I already checked [this issue](https://github.com/ResidentMario/missingno/issues/26)  and didn't work due to `TypeError
'AxesSubplot' object does not support indexing` and updated pandas and missingno based on [this issue](https://github.com/ResidentMario/missingno/issues/35). Please leave a general solution we can just by replacing different df we can use it.
Have a nice evening

**Comment by ResidentMario** [comment]
Sorry for the long response time. I assume you mean that you want to create a plot grid (via `plt.subplots`) with three elements, one or more of which is a `msno.matrix`?

I believe this is non-trivial to do because a `msno.matrix` isn't one plot, it's a `GridSpec` with two subplots: one for the matrix and one for the sparkline.

One adjustment I can make to make this easier to return a simple `plt.Figure` instead of a `GridSpec` when `sparkline=False`. That should make it easy to subplot the matrices alone.

However, if you want the full visualization including sparkline in a plot matrix, I suggest that you look into [the `matplotlib` documentation on the matter](https://matplotlib.org/tutorials/intermediate/gridspec.html).

**Comment by ResidentMario** [comment]
As of #88 there is now a `ax` parameter. Pass an existing plot axis to this parameter and the plot will appear on that axis. For example:

```
import numpy as np
import pandas as pd
import missingno as msno
import matplotlib.pyplot as plt

np.random.seed(42)
simple_df = pd.DataFrame((np.random.random((20, 10)) > 0.5), columns=range(0, 10)).replace(False, np.nan)

fig, axarr = plt.subplots(3)
msno.matrix(simple_df, ax=axarr[0])
```
Results in the following:

![subplots](https://user-images.githubusercontent.com/3466341/60838398-a06b5380-a198-11e9-92fe-13b51389dc3f.png)

**Comment by 745012770** [comment]
how can I change the subplots figure size for each msno.matrix()

**Comment by 745012770** [comment]
how can I change the subplots figure size for each `msno.matrix()`? As the 10*10 subplots of each `msno.matrix()` are too small.

**Comment by ResidentMario** [comment]
The recommended way of controlling subplot size is to manipulate the `figsize` of the subplots initializer:

```python
import matplotlib.pyplot as plt
fig, axarr = plt.subplots(10, 10, figsize=(24, 24))

# plot matrices to axarr[0][0], axarr[0][1], etcetera
```

Each subplot in this arrangement will all be the same size by default. If you want finer-grained control over layout, use [the `matplotlib` gridspec feature](https://matplotlib.org/users/gridspec.html).

**Comment by 745012770** [comment]
> The recommended way of controlling subplot size is to manipulate the figsize of the subplots initializer:
> import matplotlib.pyplot as plt
> fig, axarr = plt.subplots(10, 10, figsize=(24, 24))
> 
> # plot matrices to axarr[0][0], axarr[0][1], etcetera
> Each subplot in this arrangement will all be the same size by default. If you want finer-grained control over layout, use the matplotlib gridspec feature.
